# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: ccaa57e3e008e5fa7c2b34c13474b28a34f2934f94fd373bc76bdfa589f64fc287e97419336625240a54257f3b0dc78530ac8a519d5eb0c4f8be5a451973fbe7

test:
  secret_key_base: 8f8c1b9a9509e6c012a4a4d1c4ca53d94fc117a5b64accb47c161079afccda016ad91e9d19cf7b9aea775c688b098f9d8c19a6195cc8baaa3bad46db0f5eea46

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
